[package]
name = "medialex-scripts"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
flate2 = "1.0.28"
glob = "0.3.1"
indicatif = "0.17.7"
rayon = "1.8.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0"