[package]
name = "medialex-scripts"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
flate2 = "1.0.28"
indicatif = "0.17.7"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0"